name: WordPress Plugin Auto-Update

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Create Plugin ZIP
      run: |
        zip -r url-shorter-${{ github.ref_name }}.zip . -x "*.git*" "*.github*" "node_modules/*" "*.md" "update-version.php"
    
    - name: Create Release with GitHub CLI
      run: |
        gh release create ${{ github.ref_name }} \
          --title "URL-Shorter ${{ github.ref_name }}" \
          --notes "Automatisches Release von URL-Shorter Plugin

        ## Änderungen in dieser Version:
        - Siehe Commit-History für Details" \
          url-shorter-${{ github.ref_name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
